name: 'readmissions'
version: '0.1.3'
config-version: 2
profile: 'default'


vars:
    patient: |
        {% if var('readmissions_patient_override') is not none %}{{var('readmissions_patient_override')}}
        {%- elif var('core_patient_override') is not none %}{{var('core_patient_override')}}
        {%- else %}{{ref('claims_preprocessing__patient')}}
        {% endif %}
    encounter: |
        {% if var('readmissions_encounter_override') is not none %}{{var('readmissions_encounter_override')}}
        {%- elif var('core_encounter_override') is not none %}{{var('core_encounter_override')}}
        {%- else %}{{ref('claims_preprocessing__encounter')}}
        {% endif %}
    condition: |
        {% if var('readmissions_condition_override') is not none %}{{var('readmissions_condition_override')}}
        {%- elif var('core_condition_override') is not none %}{{var('core_condition_override')}}
        {%- else %}{{ref('claims_preprocessing__condition')}}
        {% endif %}
    procedure: |
        {% if var('readmissions_condition_override') is not none %}{{var('readmissions_condition_override')}}
        {%- elif var('core_condition_override') is not none %}{{var('core_condition_override')}}
        {%- else %}{{ref('claims_preprocessing__condition')}}
        {% endif %}

#    patient: "{{ var('readmissions_patient_override',var('core_patient_override',ref('claims_preprocessing__patient'))) }}"
#    encounter: "{{ var('readmissions_encounter_override',var('core_encounter_override',ref('claims_preprocessing__encounter')))}}"
#    condition: "{{ var('readmissions_condition_override', var('core_condition_override',ref('claims_preprocessing__condition'))) }}"
#    procedure: "{{ var('readmissions_procedure_override',var('core_procedure_override',ref('claims_preprocessing__procedure'))) }}"


model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
