name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 'default'


vars:

# # Set the input database and schema:
#   readmissions_input_database: 
#   readmissions_input_schema: 

# # Set the output database and schema:
#   readmissions_database: 
#   readmissions_schema: 
#   terminology_database: 
#   terminology_schema: 

# Say what packages are enabled:
  tuva_packages_enabled: false
  readmissions_enabled: true


dispatch:
  - macro_namespace: dbt
    search_order: [ 'readmissions', 'dbt']


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral
#    +database: dev_user