name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 'default_redshift'



vars:
### output config option 1, applies to all tuva packages
#  tuva_database: tuva
#  tuva_schema_prefix: test

### output config option 2, applies to readmissions, overrides option 1
#  readmissions_database: tuva
#  readmissions_schema: test_readmissions


### input config option 1, applies to all SmartMarts
#  core_condition_override: "{{ref('condition')}}"
#  core_patient_override:   "{{ref('patient')}}"
#  core_encounter_override: "{{ref('encounter')}}"
#  core_procedure_override: "{{ref('procedure')}}"


### input config option 2, applies to readmissions, overrides option 1
#  readmissions_condition_override: "{{ref('condition')}}"
#  readmissions_patient_override:   "{{ref('patient')}}"
#  readmissions_encounter_override: "{{ref('encounter')}}"
#  readmissions_procedure_override: "{{ref('procedure')}}"



### enabled/disabled configs

## applies to all packages
#  tuva_packages_enabled: false

## applies to readmissions only
#  readmissions_enabled: true


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral